# BSkyBlock Configuration 1.6.0-SNAPSHOT
bskyblock:
  command:
    # Island Command. What command users will run to access their island.
    # To define alias, just separate commands with white space.
    island: island is
    # The island admin command.
    # To define alias, just separate commands with white space.
    admin: bsbadmin bsb
world:
  # Friendly name for this world. Used in admin commands. Must be a single word
  friendly-name: BSkyBlock
  # Name of the world - if it does not exist then it will be generated.
  # It acts like a prefix for nether and end (e.g. bskyblock_world, bskyblock_world_nether, bskyblock_world_end)
  world-name: bskyblock_world
  # World difficulty setting - PEACEFUL, EASY, NORMAL, HARD
  # Other plugins may override this setting
  difficulty: NORMAL
  # Radius of island in blocks. (So distance between islands is twice this)
  # It is the same for every dimension : Overworld, Nether and End.
  # This value cannot be changed mid-game and the plugin will not start if it is different.
  # /!\ BentoBox currently does not support changing this value mid-game. If you do need to change it, do a full reset of your databases and worlds.
  distance-between-islands: 400
  # Default protection range radius in blocks. Cannot be larger than distance.
  # Admins can change protection sizes for players individually using /bsbadmin range set <player> <new range>
  # or set this permission: bskyblock.island.range.<number>
  # /!\ BentoBox currently does not support changing this value mid-game. If you do need to change it, do a full reset of your databases and worlds.
  protection-range: 50
  # Start islands at these coordinates. This is where new islands will start in the
  # world. These must be a factor of your island distance, but the plugin will auto
  # calculate the closest location on the grid. Islands develop around this location
  # both positively and negatively in a square grid.
  # If none of this makes sense, leave it at 0,0.
  # /!\ BentoBox currently does not support changing this value mid-game. If you do need to change it, do a full reset of your databases and worlds.
  start-x: 0
  # /!\ BentoBox currently does not support changing this value mid-game. If you do need to change it, do a full reset of your databases and worlds.
  start-z: 0
  offset-x: 0
  offset-z: 0
  # Island height - Lowest is 5.
  # It is the y coordinate of the bedrock block in the schem.
  island-height: 120
  # Use your own world generator for this world.
  # In this case, the plugin will not generate anything.
  # If used, you must specify the world name and generator in the bukkit.yml file.
  # See https://bukkit.gamepedia.com/Bukkit.yml#.2AOPTIONAL.2A_worlds
  use-own-generator: false
  # Sea height (don't changes this mid-game unless you delete the world)
  # Minimum is 0, which means you are playing Skyblock!
  # If sea height is less than about 10, then players will drop right through it
  # if it exists. Makes for an interesting variation on skyblock.
  # /!\ BentoBox currently does not support changing this value mid-game. If you do need to change it, do a full reset of your databases and worlds.
  sea-height: 0
  # Maximum number of islands in the world. Set to -1 or 0 for unlimited.
  # If the number of islands is greater than this number, it will stop players from creating islands.
  max-islands: 0
  # The default game mode for this world. Players will be set to this mode when they create
  # a new island for example. Options are SURVIVAL, CREATIVE, ADVENTURE, SPECTATOR
  default-game-mode: SURVIVAL
  # The default biome for the overworld
  default-biome: PLAINS
  # The maximum number of players a player can ban at any one time in this game mode.
  # The permission acidisland.ban.maxlimit.X where X is a number can also be used per player
  # -1 = unlimited
  ban-limit: -1
  nether:
    # Generate Nether - if this is false, the nether world will not be made and access to
    # the nether will not occur. Other plugins may still enable portal usage.
    # Note: Some default challenges will not be possible if there is no nether.
    # Note that with a standard nether all players arrive at the same portal and entering a
    # portal will return them back to their islands.
    generate: true
    # Islands in Nether. Change to false for standard vanilla nether.
    # /!\ BentoBox currently does not support changing this value mid-game. If you do need to change it, do a full reset of your databases and worlds.
    islands: true
    # Make the nether roof, if false, there is nothing up there
    # Change to false if lag is a problem from the generation
    # Only applies to islands Nether
    roof: true
    # Nether spawn protection radius - this is the distance around the nether spawn
    # that will be protected from player interaction (breaking blocks, pouring lava etc.)
    # Minimum is 0 (not recommended), maximum is 100. Default is 25.
    # Only applies to vanilla nether
    spawn-radius: 25
  end:
    generate: true
    # /!\ BentoBox currently does not support changing this value mid-game. If you do need to change it, do a full reset of your databases and worlds.
    islands: true
    # /!\ This feature is experimental and might not work as expected or might not work at all.
    dragon-spawn: false
  # Mob white list - these mobs will NOT be removed when logging in or doing /island
  remove-mobs-whitelist:
  - WITHER
  - ZOMBIE_VILLAGER
  - ENDERMAN
  - PIG_ZOMBIE
  # World flags. These are boolean settings for various flags for this world
  flags:
    CREEPER_DAMAGE: true
    OBSIDIAN_SCOOPING: true
    BIOMES_WORLD_PROTECTION: true
    PISTON_PUSH: false
    ISLAND_RESPAWN: true
    CREEPER_GRIEFING: false
    COARSE_DIRT_TILLING: true
    ENDERMAN_GRIEFING: true
    CLEAN_SUPER_FLAT: true
    CHEST_DAMAGE: false
    CHALLENGES_WORLD_PROTECTION: true
    PREVENT_TELEPORT_WHEN_FALLING: false
    NATURAL_SPAWNING_OUTSIDE_RANGE: true
    ENTER_EXIT_MESSAGES: true
    ENDERMAN_DEATH_DROP: true
    LIQUIDS_FLOWING_OUT: false
    OFFLINE_REDSTONE: true
    REMOVE_END_EXIT_ISLAND: true
    OFFLINE_GROWTH: true
    REMOVE_MOBS: true
    ENDER_CHEST: false
    ITEM_FRAME_DAMAGE: false
    TREES_GROWING_OUTSIDE_RANGE: false
  # These are the default protection settings for new islands.
  # The value is the minimum island rank required allowed to do the action
  # Ranks are: Visitor = 0, Member = 900, Owner = 1000
  default-island-flags:
    HURT_ANIMALS: 500
    DRAGON_EGG: 500
    REDSTONE: 500
    BUCKET: 500
    LOCK: 0
    ENDER_PEARL: 500
    DOOR: 500
    FURNACE: 500
    MINECART: 500
    ANVIL: 500
    FISH_SCOOPING: 500
    END_PORTAL: 500
    BREEDING: 500
    HURT_VILLAGERS: 500
    FROST_WALKER: 500
    TURTLE_EGGS: 500
    COLLECT_LAVA: 500
    LEVER: 500
    ELYTRA: 0
    RIDING: 500
    HURT_MONSTERS: 0
    ARMOR_STAND: 500
    NAME_TAG: 500
    TRADING: 0
    EGGS: 500
    ITEM_DROP: 0
    NOTE_BLOCK: 0
    FLINT_AND_STEEL: 500
    NETHER_PORTAL: 500
    CROP_TRAMPLE: 500
    ITEM_PICKUP: 0
    DROPPER: 500
    BREWING: 500
    TNT_PRIMING: 500
    COLLECT_WATER: 500
    BUTTON: 500
    FIRE_EXTINGUISH: 500
    COMMAND_RANKS: 500
    BEACON: 500
    TRAPDOOR: 500
    EXPERIENCE_BOTTLE_THROWING: 500
    PRESSURE_PLATE: 0
    DYE: 500
    ITEM_FRAME: 500
    PLACE_BLOCKS: 500
    CRAFTING: 0
    SHEARING: 500
    ENCHANTING: 0
    BOAT: 500
    BED: 500
    SPAWN_EGGS: 500
    MILKING: 0
    DISPENSER: 500
    GATE: 0
    EXPERIENCE_PICKUP: 500
    HOPPER: 500
    LEASH: 500
    BREAK_BLOCKS: 500
    MOUNT_INVENTORY: 500
    CHORUS_FRUIT: 500
    CONTAINER: 500
    POTION_THROWING: 500
    JUKEBOX: 500
  # These are the default settings for new islands
  default-island-settings:
    PVP_END: false
    PVP_NETHER: false
    ANIMAL_SPAWN: true
    LEAF_DECAY: true
    TNT_DAMAGE: true
    MONSTER_SPAWN: true
    FIRE_IGNITE: true
    FIRE_SPREAD: true
    FIRE_BURNING: true
    PVP_OVERWORLD: false
  # These settings/flags are hidden from users
  # Ops can toggle hiding in-game using SHIFT-LEFT-CLICK on flags in settings
  hidden-flags: []
  # Visitor banned commands - Visitors to islands cannot use these commands in this world
  visitor-banned-commands:
  - spawner
  - spawnmob
island:
  # Default max team size
  # Permission size cannot be less than the default below. 
  max-team-size: 4
  # Default maximum number of homes a player can have. Min = 1
  # Accessed via /is sethome <number> or /is go <number>
  max-homes: 1
  reset:
    # How many resets a player is allowed (override with /bsbadmin clearresets <player>)
    # Value of -1 means unlimited, 0 means hardcore - no resets.
    # Example, 2 resets means they get 2 resets or 3 islands lifetime
    reset-limit: -1
    # Kicked or leaving players lose resets
    # Players who leave a team will lose an island reset chance
    # If a player has zero resets left and leaves a team, they cannot make a new
    # island by themselves and can only join a team.
    # Leave this true to avoid players exploiting free islands
    leavers-lose-reset: false
    # Allow kicked players to keep their inventory.
    # Overrides the on-leave inventory reset for kicked players.
    kicked-keep-inventory: false
    on-join:
      # What the plugin should reset when the player joins or creates an island
      # Reset Money - if this is true, will reset the player's money to the starting money
      # Recommendation is that this is set to true, but if you run multi-worlds
      # make sure your economy handles multi-worlds too.
      money: false
      # Reset inventory - if true, the player's inventory will be cleared.
      # Note: if you have MultiInv running or a similar inventory control plugin, that
      # plugin may still reset the inventory when the world changes.
      inventory: false
      # Reset Ender Chest - if true, the player's Ender Chest will be cleared.
      ender-chest: false
    on-leave:
      # What the plugin should reset when the player leaves or is kicked from an island
      # Reset Money - if this is true, will reset the player's money to the starting money
      # Recommendation is that this is set to true, but if you run multi-worlds
      # make sure your economy handles multi-worlds too.
      money: false
      # Reset inventory - if true, the player's inventory will be cleared.
      # Note: if you have MultiInv running or a similar inventory control plugin, that
      # plugin may still reset the inventory when the world changes.
      inventory: false
      # Reset Ender Chest - if true, the player's Ender Chest will be cleared.
      ender-chest: false
  sethome:
    nether:
      allow: true
      require-confirmation: true
    the-end:
      allow: true
      require-confirmation: true
  deaths:
    # Whether deaths are counted or not.
    counted: true
    # Maximum number of deaths to count. The death count can be used by add-ons.
    max: 10
    # When a player joins a team, reset their death count
    team-join-reset: true
    # Reset player death count when they start a new island or reset an island
    reset-on-new-island: true
protection:
  # Geo restrict mobs.
  # Mobs that exit the island space where they were spawned will be removed.
  geo-limit-settings:
  - GHAST
  - BAT
  - BLAZE
  # Invincible visitors. List of damages that will not affect visitors.
  # Make list blank if visitors should receive all damages
  invincible-visitors:
  - BLOCK_EXPLOSION
  - CONTACT
  - CUSTOM
  - DROWNING
  - ENTITY_ATTACK
  - ENTITY_EXPLOSION
  - FALL
  - FALLING_BLOCK
  - FIRE
  - FIRE_TICK
  - LAVA
  - LIGHTNING
  - MAGIC
  - POISON
  - PROJECTILE
  - STARVATION
  - SUFFOCATION
  - THORNS
  - WITHER
  - DRAGON_BREATH
  - FLY_INTO_WALL
  - HOT_FLOOR
  - CRAMMING
  - VOID
do-not-edit-these-settings:
  # These settings should not be edited
  reset-epoch: 0
